language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3

dist: xenial

install: composer install

before_script:
  - php -r "printf('PHP %s', phpversion());"
  - composer self-update
  - composer install --no-interaction

script: ./code_check.sh