language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.2

sudo: required

dist: precise

before_install:
  - sudo apt-get -y install git zip php5-cli php5-curl

install: composer install

before_script:
  - php -r "printf('PHP %s', phpversion());"
  - composer self-update
  - composer install --no-interaction

script: ./code_check.sh