version: 2.1

commands:
  test:
    parameters:
      php_version:
        type: string
    steps:
      - checkout
      - restore_cache:
          keys:
            - vendor-<< parameters.php_version >>-{{ checksum "composer.json" }}
      - run: composer install -n --prefer-dist
      - save_cache:
          key: vendor-<< parameters.php_version >>-{{ checksum "composer.json" }}
          paths:
            - ./vendor
      - run: ./vendor/bin/phpunit --stop-on-failure

executors:
  php:
    parameters:
      php_version:
        type: string
    docker:
      - image: circleci/php:<< parameters.php_version >>

jobs:
  code_analysis:
    executor:
      name: php
      php_version: "7.3"
    steps:
      - checkout
      - restore_cache:
          keys:
            - vendor-7.3-{{ checksum "composer.json" }}
      - run: composer install -n --prefer-dist
      - run: ./vendor/bin/phpcs --standard=.phpcs.xml src
      - run: ./vendor/bin/phpcs --standard=.phpcs.xml spec --exclude="PSR1.Methods.CamelCapsMethodName"
      - run: ./vendor/bin/phpcs --standard=.phpcs.xml tests
      - run: ./vendor/bin/phpspec run
  sonar_scan:
    docker:
      - image: gcr.io/opnf-management/sonar-scanner:latest
        auth:
          username: _json_key
          password: $GCLOUD_SERVICE_KEY
    steps:
      - run: /opt/run-scan.sh
  # test_php56:
  #   executor:
  #     name: php
  #     php_version: "5.6"
  #   steps:
  #     - test:
  #         php_version: "5.6"
  # test_php70:
  #   executor:
  #     name: php
  #     php_version: "7.0"
  #   steps:
  #     - test:
  #         php_version: "7.0"
  # test_php71:
  #   executor:
  #     name: php
  #     php_version: "7.1"
  #   steps:
  #     - test:
  #         php_version: "7.1"
  # test_php72:
  #   executor:
  #     name: php
  #     php_version: "7.2"
  #   steps:
  #     - test:
  #         php_version: "7.2"
  # test_php73:
  #   executor:
  #     name: php
  #     php_version: "7.3"
  #   steps:
  #     - test:
  #         php_version: "7.3"

workflows:
  version: 2
  build:
    jobs:
      - code_analysis
      - sonar_scan:
          context: Google Container Registry
          requires:
            - code_analysis
      # - test_php56
      # - test_php70
      # - test_php71
      # - test_php72
      # - test_php73
